services:
    proxy:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - frontend
            - backend
        depends_on:
            php:
                condition: service_started

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            target: development
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
                XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
                XDEBUG_MODE: develop,coverage,debug,profile
                XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
                XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
                XDEBUG_LOG: /dev/stdout
                XDEBUG_LOG_LEVEL: 0
        user: "${UID:-1000}:${GID:-1000}"
        volumes:
            - ./:/var/www/app
        networks:
            - backend

    postgres:
        image:  postgis/postgis:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - backend

    redis:
        image: redis:latest
        sysctls:
            - net.core.somaxconn=511
        ports:
            - "6379:6379"
        volumes:
            - redis:/data
        networks:
            - backend

    workspace:
      build:
        context: .
        dockerfile: ./docker/php/workspace.Dockerfile
        args:
          UID: ${UID:-1000}
          GID: ${GID:-1000}
          XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
          XDEBUG_MODE: develop,coverage,debug,profile
          XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
          XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
          XDEBUG_LOG: /dev/stdout
          XDEBUG_LOG_LEVEL: 0
      ports:
        - "5173:5173"
      tty: true
      stdin_open: true
      volumes:
        - ./:/var/www/app
      networks:
        - backend
        - frontend

    ssr:
      build:
        context: .
        dockerfile: ./docker/php/workspace.Dockerfile
        args:
          UID: ${UID:-1000}
          GID: ${GID:-1000}
          XDEBUG_ENABLED: false
      entrypoint: ["php", "artisan", "inertia:start-ssr"]
      tty: true
      stdin_open: true
      volumes:
        - ./:/var/www/app
      networks:
        - backend
        - frontend

networks:
    backend:
    frontend:

volumes:
    postgres:
    redis:


